### PR TITLE
Add support for `[text](@cite key)` syntax

### LINKED ISSUE #63: Allow arbitrary link texts
Just like `Documenter.jl` in general supports arbitrary link texts with the syntax [`[Custom Header](@ref my_custom_header_name)`](https://documenter.juliadocs.org/stable/man/syntax/#Duplicate-Headers), `DocumenterCitations.jl` should support the syntax `[text](@cite key)`, which simply renders as [text](http://aliramadhan.me/DocumenterCitations.jl/dev/references/#Mayer2012).

Especially in [docstrings](http://aliramadhan.me/DocumenterCitations.jl/dev/#DocumenterCitations.Example) I would often want to include a "manual" list of references, e.g.

```
# Reference

* [Mayer, Krechetnikov, Phys. Rev. E 85, 046117 (2012)](@cite Mayer2012)
```

which may also be the underlying motivation of #62. The generalized syntax might also partially address #15 and #32.

### PR DESCRIPTION
**Pull request by goerz**
Closes #63

### CODE REVIEW

**Comment by fredrikekre** [comment]
This is great! I was just about to implement this but looked and open PRs and found this. I think that https://github.com/ali-ramadhan/DocumenterCitations.jl/blob/13f5a732794e9a25ba08470b2c030b2644e83cde/src/citations.jl#L28 is only true for the `[key](@cite)` style, in general.

**Comment by goerz** [comment]
For the record, this functionality is also fully implemented in [QuantumCitations](https://juliaquantumcontrol.github.io/QuantumCitations.jl/stable/), which is my fork of DocumenterCitations.

**Comment by fredrikekre** [comment]
Ok... Why not contribute to existing packages to join efforts instead of forking?

**Comment by goerz** [comment]
I tried, with this PR. Unfortunately, DocumenterCitations seems to be unmaintained. There’s also a question of control: if I’m depending on a plugin like this in the documentation of my projects, I need to have a fair amount of control to implement any feature I might need. My preference would have been to extend this package instead of forking, but that would require an active and responsive maintainer. This is not a criticism of @ali-ramadhan, but a fork seemed like the way to go here. That being said, QuantumCitations could in principle be backported, although there are large parts that were substantially rewritten to support “citation order” / only listing cited entries in the bibliography.

**Comment by vchuravy** [comment]
Maybe it would make sense to move this package to JuliaDocs?

**Comment by fredrikekre** [comment]
I can invite @ali-ramadhan to JuliaDocs if you want to transfer it there.

**Comment by goerz** [comment]
I’d certainly be open to (co-) maintaining this package within the JuliaDocs org, but it’s up to @ali-ramadhan

**Comment by goerz** [comment]
@simonbyrne and @LazyScholar seem to also have had maintainer access in the past

**Comment by simonbyrne** [comment]
I agree it would make sense to move, but I don't have admin access. @vchuravy is Ali still at MIT? Can you reach out to him?

As far as this PR goes, a test and/or example that uses this would be helpful.

**Comment by fredrikekre** [comment]
Bump @ali-ramadhan 🙂

**Comment by navidcy** [comment]
@ali-ramadhan?

**Review by charleskawczynski — COMMENTED** [review]
Can we somehow add a test?

**Comment by simonbyrne** [comment]
Given that the current admin is missing, we could also just fork it to JuliaDocs and move development there (similar to what we had to do for https://github.com/JuliaFolds2)

**Comment by fredrikekre** [comment]
Forked: https://github.com/JuliaDocs/DocumenterCitations.jl

**Comment by goerz** [comment]
> Can we somehow add a test?

I'm not going to pursue this PR further in its current form. For context, this PR was a "test balloon" to see if `DocumenterCitations` was open to contributions (which it currently is not). Hence, I forked the package. The full feature, including extensive tests, is implemented in the forked [QuantumCitations.jl](https://juliaquantumcontrol.github.io/QuantumCitations.jl/stable/). That fork also includes several other additions which would close #61, #26, #22, and #14. However, it also turned into a substantial rewrite, including some changes to how the citation pipeline runs. This was necessary to enable my preferred numbered citation schemes, where the citations are numbered in the order they appear throughout the entire documentation. This required separating "collecting" citations from rendering them.

There are still some limitations, most notably a "bug" in Documenter described in https://discourse.julialang.org/t/running-makedocs-overwrites-repl-docstrings/95982. This would be fixed in Documenter 0.28 (whenever that will come out), and the changes in Documenter 0.28 would also allow for doing some more advances rendering of citations, such as collapsing the citations in the first paragraph of https://juliaquantumcontrol.github.io/QuantumControl.jl/stable/, which should render as "[1-8]". However, Documenter 0.28 is *very* breaking, and might again require some fairly extensive restructuring in DocumenterCitations/QuantumCitations, which I'm planning to make when that version comes out (and I have some spare time).

The `QuantumCitations` package is functionally backward compatible with `DocumenterCitations`, except that the defaults are different. If I was going to backport all the functionality into `DocumenterCitations`, I could again make the [Author-year style](https://juliaquantumcontrol.github.io/QuantumCitations.jl/stable/gallery/#author_year_style) the default, and just switch my packages to the [Numeric style](https://juliaquantumcontrol.github.io/QuantumCitations.jl/stable/gallery/#numeric_style).

Thus, from my perspective, the way to go would be

* DocumenterCitations gets forked to the JuliaDocs organization
* Documenter 0.28 comes out
* I adapt QuantumCitations to Documenter 0.28
* I make a wholesale PR to DocumenterCitations to introduce all the changes from QuantumCitations. Basically, this will come down to renaming QuantumCitations to DocumenterCitations and changing the default to be "Author-Year" style, so as not to break rendering for existing users.
* Additional features such as collapsing citations will be added to the new DocumenterCitations.
* QuantumCitations will either go away or become a light-weight package that simply switches the default style to numeric

There would have to a responsive maintainer for the JuliaDocs/DocumenterCitations fork to oversee this… Or if you wanted to add me as a maintainer there, I could just go ahead and do the rewrite when the time comes.

Another thing you could do, if you want to jump ahead a little, is to fork QuantumCitations (instead of DocumenterCitations) to JuliaDocs, but rename it to DocumenterCitations. Then once Documenter 0.28 comes out, I can make PRs there to adapt to that, and then after some period of time a new breaking release of DocumenterCitations could be registered, based on JuliaDocs/DocumenterCitations

**Comment by fredrikekre** [comment]
You should already have gotten an invitation.

**Comment by fredrikekre** [comment]
Lets discuss the next steps in https://github.com/JuliaDocs/DocumenterCitations.jl/issues/1

**Comment by goerz** [comment]
> Lets discuss the next steps in [JuliaDocs#1](https://github.com/JuliaDocs/DocumenterCitations.jl/issues/1)

Yes… I'll get back to you there later tonight

> I'm not going to pursue this PR further in its current form.

So, I'm just going to close this for now, and we can revisit the issue over at JuliaDocs

**Pull request closed without merging**
