### PR TITLE
Don't print year twice in bibliography

### LINKED ISSUE #43: Year is printed twice
Looking at http://aliramadhan.me/DocumenterCitations.jl/dev/references/ the years are printed twice (after the names and at the very end). That's strange. It also happens in our docs (where I noticed it first).
```
Mayer2012
H. C. Mayer , R. Krechetnikov (2012), Walking with coffee: {Why} does it spill?, Physical Review E, 85, 046117, 2012 
```

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #43 for me

### CODE REVIEW

**Comment by fingolfin** [comment]
CC @ThomasBreuer

**Comment by LazyScholar** [comment]
`Bibliography.jl` introduces a annoying space before the comma.

**Comment by LazyScholar** [comment]
Not sure if doing it wrong. I think i merge it as the 'space coma space' was there before and a fix in `Bibliography.jl` will fix that automatically.

**Comment by fingolfin** [comment]
I have a fix for the space, it just spiraled out of control as I kept finding more and more bugs 🤣 I'll submit more PRs here and in related repos soon

**Comment by fingolfin** [comment]
See https://github.com/Humans-of-Julia/Bibliography.jl/pull/23

**Comment by LazyScholar** [comment]
Yeah i noticed. Thank you for going on a issue hunt.

**Pull request merged**
