### PR TITLE
Fix for KeyError in expand_citations

### LINKED ISSUE #55: When using `doctest=:fix`, I get `ERROR: KeyError: key Markdown.Code(...`
When trying to "fix" doctests for our project, I get the following error in Julia 1.6.5, with Documenter v0.27.10 and DocumenterCitations v0.2.11 and also DEV
```
julia> Documenter.doctest(Oscar; fix=true)
[ Info: SetupBuildDirectory: setting up build directory.
[ Info: Doctest: running doctests.
┌ Warning: could not find code block in source file
└ @ Documenter.DocTests ~/.julia/packages/Documenter/qdbx6/src/DocTests.jl:421
[ Info: Skipped ExpandTemplates step (doctest only).
[ Info: Skipped CrossReferences step (doctest only).
[ Info: Citations: building citations.
┌ Error: Doctesting failed
│   exception =
│    KeyError: key Markdown.Code("@meta", "CurrentModule = Oscar\nDocTestSetup = quote\n  using Oscar\nend") not found
│    Stacktrace:
│      [1] getindex(d::IdDict{Any, Any}, key::Any)
│        @ Base ./iddict.jl:93
│      [2] expand_citations(doc::Documenter.Documents.Document)
│        @ DocumenterCitations ~/.julia/packages/DocumenterCitations/syRlI/src/citations.jl:15
│      [3] runner(#unused#::Type{DocumenterCitations.Citations}, doc::Documenter.Documents.Document)
│        @ DocumenterCitations ~/.julia/packages/DocumenterCitations/syRlI/src/citations.jl:8
│      [4] dispatch(#unused#::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Documents.Document)
│        @ Documenter.Utilities.Selectors ~/.julia/packages/Documenter/qdbx6/src/Utilities/Selectors.jl:170
│      [5] #2
│        @ ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:266 [inlined]
│      [6] cd(f::Documenter.var"#2#3"{Documenter.Documents.Document}, dir::String)
│        @ Base.Filesystem ./file.jl:106
│      [7] makedocs(; debug::Bool, format::Documenter.Writers.HTMLWriter.HTML, kwargs::Base.Iterators.Pairs{Symbol, Any, NTuple{6, Symbol}, NamedTuple{(:root, :source, :sitename, :doctest, :modules, :doctestfilters), Tuple{String, String, String, Symbol, Vector{Module}, Vector{Regex}}}})
│        @ Documenter ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:265
│      [8] (::Documenter.var"#all_doctests#32"{Bool, Vector{Regex}, Vector{Module}})()
│        @ Documenter ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:874
│      [9] macro expansion
│        @ ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:895 [inlined]
│     [10] macro expansion
│        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
│     [11] doctest(source::String, modules::Vector{Module}; fix::Bool, testset::String, doctestfilters::Vector{Regex})
│        @ Documenter ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:895
│     [12] doctest(package::Module; manual::Bool, testset::Nothing, kwargs::Base.Iterators.Pairs{Symbol, Bool, Tuple{Symbol}, NamedTuple{(:fix,), Tuple{Bool}}})
│        @ Documenter ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:830
│     [13] top-level scope
│        @ REPL[59]:1
│     [14] eval
│        @ ./boot.jl:360 [inlined]
│     [15] eval_user_input(ast::Any, backend::REPL.REPLBackend)
│        @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:139
│     [16] repl_backend_loop(backend::REPL.REPLBackend)
│        @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:200
│     [17] start_repl_backend(backend::REPL.REPLBackend, consumer::Any)
│        @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:185
│     [18] run_repl(repl::REPL.AbstractREPL, consumer::Any; backend_on_current_task::Bool)
│        @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:317
│     [19] run_repl(repl::REPL.AbstractREPL, consumer::Any)
│        @ REPL /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:305
│     [20] (::Base.var"#875#877"{Bool, Bool, Bool})(REPL::Module)
│        @ Base ./client.jl:387
│     [21] #invokelatest#2
│        @ ./essentials.jl:708 [inlined]
│     [22] invokelatest
│        @ ./essentials.jl:706 [inlined]
│     [23] run_main_repl(interactive::Bool, quiet::Bool, banner::Bool, history_file::Bool, color_set::Bool)
│        @ Base ./client.jl:372
│     [24] exec_options(opts::Base.JLOptions)
│        @ Base ./client.jl:302
│     [25] _start()
│        @ Base ./client.jl:485
└ @ Documenter ~/.julia/packages/Documenter/qdbx6/src/Documenter.jl:884
```

### PR DESCRIPTION
**Pull request by fingolfin**
Fixes #55 for me.

### CODE REVIEW

**Comment by fingolfin** [comment]
@simonbyrne @LazyScholar does this look sensible?

**Review by charleskawczynski — COMMENTED** [review]
LGTM, can we somehow test this?

**Comment by fingolfin** [comment]
It sure would be good, and if there were existing tests, I'd have tried to add one foe this patch. Alas, there are no real tests other than for some low level helpers :-(.

I think a good way to add tests to this package (which are lacking in general) would be to build an actual manual (eg that of the package itself) as part of the tests, and then compare the generated files to some reference versions (to detect changes; one may want to use a pinned version of Documenter for that... and/or specifically test against different Documenter versions to make sure it keeps working with both old and new versions...).

**HOWEVER** I do not have the time to write such a setup, sorry. If someone else does I could try to figure out how to add a test for this specific issue.

Of course other tests could be done that test parts of the code more specifically but I wouldn't know where to start. And how to so it w/o relying on undocumented parts of Documenter (not saying it isn't possible just that I lack the expertise).

BTW tracking code coverage for the test suite also would be nice.

**Comment by fingolfin** [comment]
I've added a simple test now, after I realized that even `doctest(DocumenterCitations; fix=true)` fails right now. PR #57 adds that test (but of course has failing CI) while this PR passes CI.

**Comment by charleskawczynski** [comment]
I guess, regardless of the tests, these changes look reasonable to me, so I'm fine with these changes overall. But it'd be nice to get feedback from others

**Comment by simonbyrne** [comment]
Thanks!

**Pull request merged**
