### PR TITLE
add conversions for TeX diacritical marks

### PR DESCRIPTION
**Pull request by simonbyrne**
Based on
- https://en.wikibooks.org/wiki/LaTeX/Special_Characters
- https://en.wikipedia.org/wiki/Combining_Diacritical_Marks

### CODE REVIEW

**Review by ali-ramadhan — APPROVED** [review]
Nice! In a future PR might be good to add a reference with diacritical marks to `example.bib` so the docs (which also serve as an example) show that we can support diacritics.

**Comment by simonbyrne** [comment]
Added an example.

**Comment by simonbyrne** [comment]
Unfortunately it doesn't quite work due to https://github.com/Azzaare/BibParser.jl/issues/5

**Comment by charleskawczynski** [comment]
☹️ hopefully, we don't run into this too much initially 🤞🏻

**Comment by Azzaare** [comment]
This is a problem of [BibParser.jl](https://github.com/Azzaare/BibParser.jl) I was planning to tackle eventually.

The current bibtex parser is not satisfying, and I will need some time to improve it. I hope I can take care of it next month (I have my hands full at the moment). I know some database for conversion of LaTeX special characters and diacritical marks are available online, I hope to write a script to generate the Julia code to handle both.

**Pull request merged**
